In [2]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [74]:
df = pd.read_csv('dataset.csv')
df = df.drop(columns = 'Unnamed: 0')

#pd.concat(g for _, g in df.groupby("track_name") if len(g) > 1)
pd.options.display.max_rows = None
df[df['track_genre']=="hip-hop"]

                     track_id  \
51000  1aL9518P5G72N92b48tuKw
51001  08Isz2ETWSBhvIl8UpKYsp
51002  42TMa2hgBNjte4uV7jNCnQ
51003  3UhmuWcFaLS3AO3kI9ynQ2
51004  5HCyWlXZPP0y6Gqq8TgA20
51005  3wz2vWhYnnBoFmgMkqtzLy
51006  7AsG1F1eMWd17RYan8M3Wm
51007  7IK26RNUdgoZWJdlarrcty
51008  2AilvPt1AQ8PixlCKqkjfj
51009  32FVH23yFXr8Z0sfjRw4It
51010  29m79w9xPMH4YCD6r8JSmV
51011  6ZYxNjuAU9Vy3VtF6W1dtE
51012  5RrOyaV2xOAnf62uWj24dB
51013  2uThc9fZx2BEL3t6uuRMO1
51014  70wFZWY6cKFxp3Qcq8uxH4
51015  2ZRo7axmMPeSVUvDbGkJah
51016  58f4twRnbZOOVUhMUpplJ4
51017  3sqRODOZ1Z6hR4F2tnFAlg
51018  6XPmY4hIb1RGRyNuq0UBsl
51019  6TClJ8jXi3OBV7gcrU3jx5
51020  1W1dS4VnIrYnllQJ3CAcZy
51021  0a6zRnrjmaOcqsEIFkXIhw
51022  0yCWDaAgOtg6TKlNCg9rwA
51023  7B4uYqxTpTOS1sgxFB9Ann
51024  2NTVtNcpC0i1R7LVGaCZCF
51025  60YICjIPdL7LDBcCMK0tAk
51026  7cVe3mYMIfhOlz1NXFWv70
51027  5pcmtf1lwrMqmAWWm248fY
51028  5W7DOVGQLTigu09afW7QMT
51029  5uHy68Q7ZWe8Qq9k7EAprS
51030  2tjWCe2W7sgvS3C8NHcdtI
51031  2PcGqmKToUz0s65q1Acg7d
51032  7mNZUnDWUDidWBFaUpVtOC
51033  1w3exvIgbRFV2ijf6qyWm8
51034  6udC4b4jOSnHb9ItnXgKLR
51035  3JkVYvxNoGf2HCWJo61462
51036  6FQQiTpYnfc5803p84bQp1
51037  3Vb8KkT6Ub5fFGPYJCJyLh
51038  5D507IC1VOAg7bKkmOblr6
51039  0MHiYjjcHNYM9KURa6NveF
51040  209pScL6fUhISxcLWkB6rf
51041  2vkNA9I029dTwX0y6d59Sc
51042  4wCy7erulqUfFQNVaZBD9b
51043  6eYsOcDdB5b6rTO5ubMxeV
51044  5WWplXimzIjlJiN2N7T9Q3
51045  6yvxu91deFKt3X1QoV6qMv
51046  6A6mDExVoAEJmc5JyVSQeK
51047  4HdzYTQiouB9BVYX7JOrhh
51048  1Hdz67JES35Z4h3Yd4PXvV
51049  0xttqqTj7ZAGyVkfOYxQ4F
51050  27NovPIUIRrOZoCHxABJwK
51051  0e8nrvls4Qqv5Rfa2UhqmO
51052  3D0pmiK3zyF9PudyJ8mkor
51053  65c6VCikt7f5sAS1heoYQC
51054  3iICKiDTyIK5qoVl2hXB2f
51055  4faDlXyZMSxEuxBdd5gDIz
51056  1418IuVKQPTYqt7QNJ9RXN
51057  7m4CgL81VVIHaaiSxyH922
51058  5gSVKG0R4xc8qtDIoyDNy8
51059  3GVkPk8mqxz0itaAriG1L7
51060  27ZZdyTSQWI7Cug2d2PkqV
51061  0l1i3nJ4aDMk0inxnvzYTz
51062  2JzZzZUQj3Qff7wapcbKjc
51063  6SPLYHHBN0dKGaoD2Jcccs
51064  2gNMXJDKRmKWuevBGjN8wo
51065  1QZRCi2Z1DQQaR6bGAzhtN
51066  3T0oPETOdddxJ2xTt2qJe4
51067  4Mh04VNolWA9g97ychP72l
51068  4FcknXDJ8yW2QYUl0cm6uJ
51069  7wW9scVNLYFLsmBb1yAUmS
51070  1skGwRjc7wYY70PJCAkKMr
51071  5yj7D4UllTkAccTmROibCQ
51072  3Vmo13MxVRKBszmfK61ONH
51073  2vR23BjIzpLMtzsyKrM6Mb
51074  5eGsHi6RcL33gb9k89UYaB
51075  0Id2IzhR3w50aP2PHfMUE3
51076  57DhVYA7E1CyrE4OKuyLb7
51077  3NpbGCDrcQTERaZb5dHhd3
51078  5ZTsPwtt7aCuzbWd5rDGys
51079  3k9PtGmPNnQtt32TKWm6f3
51080  0wGrTrI43CKmfzbFNNhftb
51081  2MwCoo4GeXpi8soWn9EiPo
51082  0JBnAsReYppHqCZJbqy5H8
51083  6Kynli1iHBqJRWUCohcV9h
51084  7tZQznsUajYIVj4IwALXmz
51085  36cqlmc53NqlEUqPJdgUOx
51086  2hTn8oS49IQULxAWs7hEBz
51087  2zQE8TE5BQDJA11ggnope9
51088  5PjdY0CKGZdEuoNab3yDmX
51089  7FcQRdlqMvAKmQH1SXCk1s
51090  2hDMBVN3P47GEhH5VtmA6m
51091  5iUbq311UD3MZYmfi2a1Ob
51092  7H3mfOvtPNA8YDF3EdKy0L
51093  1UUgngRGzFWfgpyN0WAN1r
51094  2PEo8JQ48mfEv8a2HLqDvt
51095  1aQ58u4guUf999iQX3J2HF
51096  6XmBh5HSdVzEAaqzEftL9t
51097  6sPW145Y3LSXd4p1LjBOcS
51098  6NwEpX2JUWHVKWfDDfcqC4
51099  6zdikHQs2PBFgGIZBxqOeV
51100  5ZKG94fnjiuMH5yrC5S9lS
51101  1DIXPcTDzTj8ZMHt3PDt8p
51102  5DqdesEfbRyOlSS3Tf6c29
51103  4t22MCG1GHjKlXRCIlJlDd
51104  4hzDCJUFDyk66oIBirPiCl
51105  7tbzfR8ZvZzJEzy6v0d6el
51106  7Lvxcrbzuz1mNCPkFakS9K
51107  75Ak0cit8hV604Wjlq1gf2
51108  3oWv5qDKYN7MH6FdlglMN5
51109  0gmEt2nKOssVRStyUmjSpE
51110  3ee8Jmje8o58CHK66QrVC2
51111  5ZsAhuQ24mWHiduaxJqnhW
51112  1ZMq0qzXfGnFo7BN03yddJ
51113  3X3BiiDYiPVIn5gEpO9HiF
51114  1pW5BQT2ltq0NPSlbkev0v
51115  3ubdbuynat3QLfKtdtJ5BH
51116  6qS40yL7kXVoChI8SSCQIQ
51117  2jt9VV6QGn0tbwkrr26OO6
51118  1TRgZ55GFCKSbrTb62rmra
51119  16xg7UwH9hbs96vCD8k6bC
51120  60suOlM8VpTVITPFeqth8r
51121  47Rqh5ZSamtIOFi7G6VgFJ
51122  6HGoVbCUr63SgU3TjxEVj6
51123  6qCNaRRr5xJALfNJvh0NAw
51124  3uHisD8WxXOYLaxeOl098L
51125  7gFzBppKTiKAs38SWOjbO6
51126  2NBYiYtI4v1ujkhHZBq3xw
51127  19EZKr7Kf0XWCcspyWL8Rp
51128  1SC5rEoYDGUK4NfG82494W
51129  5eN1nmOe9R29OBL6soTJov
51130  2mKvEIvd912eg3FZ8WamMS
51131  7rlulUEMn27TLbdHpNPugE
51132  6C8JJFoGC4dkVtAHVK3iif
51133  39ujbBjTwwqUFySaCYDMMT
51134  0nsZBSzz5WG7onOtEL5mqj
51135  06fRsW6JDm7WPQWrmrMak2
51136  1JWWwXFfNKi6ioDZOaa9jX
51137  12LE4Omy9ze8xTOMofMVB3
51138  3FQwvjvKnE3O4YKawVUNpA
51139  525NKU3UFgZQtCXWBWE0al
51140  1zAkNzJZVPrWDCnowb1vpZ
51141  3lRzVvMNG1QJcHlhLXM0lA
51142  038oBXqL9ttCHHZmNrYxQk
51143  3yqkV2Vd0u4l9lUnlaFNZT
51144  1PaxAUxLEVpi75l0nDtwu1
51145  2dpMdklbSc5CmZ3ijhknZ5
51146  5KDEqPWSBZzrANHGBlJ8xN
51147  08QN1e5ou2ANfx9AhB88nw
51148  6JHmmaJRB6OFZa7hjfxAfc
51149  0zsA45R0SQPfqC5TyDOqY8
51150  3B54sVLJ402zGa6Xm4YGNe
51151  0JP9xo3adEtGSdUEISiszL
51152  4IQqOlTZpfjnSTOArpZX5j
51153  6qJrmD6CXKWkWcsYwu9AV3
51154  7tpRgru0h8B4eCvdBegLTA
51155  0Z2SFlnXH9yMN36djUeqyE
51156  0C4KChnQFHNgtjbppUFooH
51157  0YLSjVxSb5FT1Bo8Tnxr8j
51158  1xSCr5uIndaHKFdO4s2V6B
51159  7lQ8MOhq6IN2w8EYcFNSUk
51160  0HTb4JfMtMkMYUtyd19In3
51161  51hrri99KuNwhALxbRRJnq
51162  0M4HcGtxIWVVH4rSNp6XhQ
51163  4Q3D7EnZNDNnIZsfjSbGkh
51164  2VGs7EmaIxq96Wcog6DQOc
51165  7MdX25DW2YXXwCWl8fSHnq
51166  1v8NfOckFEnck9gp7iyetm
51167  6q9XTgfWilsnyiFofvYrIF
51168  0mvcsYusnTYlAkOZ077lDb
51169  3Blsc8iWj4LLgnCe0DhnU0
51170  4hAmLeBT1Ryk2oxSMMiJ7z
51171  0MYof8K1RPjc1Htnr7CDa6
51172  4oglYe270D9yn6Gc0JWc03
51173  2V52mICuJnWB3C4lrJZd7v
51174  1kJL5ouqpWRitSej8fdTor
51175  1rhSz40cKH9mzrlJKhg0E4
51176  70rQq4iMDKjX8UlG7QlHUa
51177  2ldVpRwLjfUWCDqrjNQYWt
51178  7FNClArpU0MQIIkAU5VSwh
51179  27XJv9grlenIhZEPpDdnIY
51180  1O00WM9qGLUBA5gq2yw0WF
51181  0yy3WShigK5eqAmhS4aRwz
51182  1dVZeuQFWzSI22d3hPEncI
51183  0t0mHozF8Xsif9w8bemh9D
51184  79hVM41bj2IKfCVhUFh9Ra
51185  6qMj7ctUqGyqWaSh62I4I4
51186  0fGclndst25Qqy8j4u5De5
51187  5vyRNIsjHH6pZu1dKBddOO
51188  0zhxUjkXag9iEFccaiua4a
51189  0vp47IigZ7JVQ89jDetO7H
51190  5jXwDTzWWPK4AzJwHEHdkQ
51191  6EwRpLL5QThnF2k1sZzQpC
51192  5omEZ9V6ytpM0WNBcIOavc
51193  20vLGVDLfbzdh3vbSpSuj8
51194  7K96XKPXv0xPKetFRB7Zh6
51195  7qhOEYwWarxO50hAZkEY59
51196  2T1SNgLERipx3n6iVTeHZA
51197  3AedlLCGKNhQdhtLzObIbR
51198  2x8gjYPcomasunXlQ4gA2i
51199  0bhhXULPNfCsVhZp35HrC3
51200  0VgkVdmE4gld66l8iyGjgx
51201  7m9OqQk4RVRkw9JJdeAw96
51202  2qgXrzJsry4KgYoJCpuaul
51203  3F5CgOj3wFlRv51JsHbxhe
51204  4fyR24BKznXBLNkK8LwWla
51205  3Ofmpyhv5UAQ70mENzB277
51206  5DVnSQ90r2M3gm6XbgTCLp
51207  2JHX4L5wNhzxVMPwc7UMAw
51208  7AW4g4I9fPfUIyqtbsuAkM
51209  4Znd47cztY1DEmoWWVcP74
51210  7sp9SYjIBBniAJ7xa1nkZh
51211  7rXDc2ImBGwcypUFbNqbFB
51212  1rhSz40cKH9mzrlJKhg0E4
51213  2oiffhYxrg5NHiPDZubyqa
51214  7i06j7x2UzGnURlzGV37WL
51215  0I3wA6Iy9HF8uW38es7Tb1
51216  3yfqSUWxFvZELEM4PmlwIR
51217  3MxwkxdOyQxGjT3UeOqCEk
51218  7xHG6LdShPMXeL5SllDprP
51219  2xpkJFCKCevn863vXJli7S
51220  7af1WixhIA44jYgzXU19da
51221  1dVZeuQFWzSI22d3hPEncI
51222  1v1nsB6TCXuhdC4QNP4aB4
51223  43VoASYNFFXqy2HE0rAm4W
51224  1iKqYeWSuNtpiv1L9IGAbB
51225  511zIRlXGOQs2oykDi4KwT
51226  5wPayKgEqHa0ewZhUS8BSY
51227  4lLahP9nb19QJux8cSXSIX
51228  27sqBDytiRE42WplwCLrj7
51229  2xXAcD0zzapYgSl5z1A847
51230  1qdiryo9D6QgoZw9beV72q
51231  62ppSZlSrkdflEZWXM34gG
51232  3ufMt1JWzgGeJ1rvGjeGbX
51233  3ZPrcLz9peBVWyYZHwx0DI
51234  5OotwkHgMpNYfsCwAOs4jP
51235  5Y35bkxA5od9mlkPuN9Tit
51236  0w6KXQRbURk23AtKn3q5Wr
51237  2T1SNgLERipx3n6iVTeHZA
51238  0S6JhgDleukTFLOMlIuiZI
51239  7cS2YS8Q5wJ7ZzqbKLsuFR
51240  7maprFc3lpb4PSq3290wk3
51241  0tNLlw94DIrCECnp0dSUUz
51242  0c9wSzwT33NaUlJNy1z0jh
51243  4nSwWiwtieiNmRAjy9fEXN
51244  4u9jtJXU6fAbBBmWL6VB0E
51245  1H25cHqoclhvwvl7BPyCbW
51246  2Vag8ExVU4vAFj1FVvw0yC
51247  6TFUGAC1zk57FICwy1wZNW
51248  2mBTuHj5xrXHF3BeXD9ebN
51249  5bWsrvSklKrDrYbBgqknno
51250  6DCZcSspjsKoFjzjrWoCdn
51251  0F7FA14euOIX8KcbEturGH
51252  3yRLROmAcKJBqTrdEczFB8
51253  7floNISpH8VF4z4459Qo18
51254  67BtfxlNbhBmCDR2L2l8qd
51255  71VXewVKFs0HcwEom489zH
51256  0cpyy8xLYRt1OdlnqPmMnm
51257  2r32XiAWtZbT3eLUvf4pag
51258  4ggG5qVYvi1tzluIU0MXoo
51259  38T0tPVZHcPZyhtOcCP7pF
51260  20EQiQQYSyuifv6YMj64qP
51261  7GNRUsU3M4XNDDB9xle5Dz
51262  1XdUEm2MwB6ysy6E80ltMg
51263  5zUPoHkgqAr1XwTMNzNtGs
51264  6dgYHmc5yBnQFI4FSCbp6y
51265  1J9OoW4eLxIjwo10lBB83x
51266  5qoxoGIbLCLSMJXpxr5COw
51267  2Uik6DjW1n5CWbRNdZilV5
51268  5XsoDbDt98b0FkFLOhsJuS
51269  5Z9KJZvQzH6PFmb8SNkxuk
51270  1t25hKpVYInuzw2opW97yJ
51271  71Udwiv5GsZghU6XQ5LXQj
51272  2erjvSbTPKGalbZZhPgcCL
51273  7I4JOGn1A3GzTiaEMsp3Ur
51274  455OjhLhU9JCNYKKoUOFwr
51275  2109dBho14Lqh2wr8goqAP
51276  5uaIbU3oHHcSOK6WFNK5nj
51277  4xkOaSrkexMciUUogZKVTS
51278  18oO0TSyS9lIW9sioZyCNN
51279  0OvC1QkWdBI3ORrp2lEhNO
51280  5aa4zMfrJ16iDnS6UIKtlL
51281  6dUGQzqCA18wKzVuiGttJF
51282  2SazZ5d4m9G5IWu5xdMjZf
51283  5tIr2cGQsj0oeqLk2tAU0L
51284  4beibTdsFNXHq7bosci34R
51285  39vrbjCMTRXEdiIr2IsBgd
51286  0kzmBBR1Jjx5zBZKx9lsJr
51287  6sAdmaffuMijDszeFrGF1H
51288  1lIb7Ze8PHhWwdXDtPF00j
51289  7fttjqzmvgvpRQoOzyYng3
51290  0qvoxfYodIfe14gaidhnsV
51291  61gu4XQFyAfIUneEyW4EJu
51292  6Ozx2ngGtXrqznTKhKBlrT
51293  3mVpbUvLXvzPH2zL0p7Q2U
51294  4d3tiblcaqGdji7XvPGHiq
51295  1vnDu8pbmwz88G6RDugerQ
51296  4RbRZYPR7Dwg8WRNn4UA8m
51297  5NEGfbKMcNuEWOzpWufScA
51298  3LEMmV0BgtM7TaJk40PFZU
51299  6P8dmbcOEz7XPFQjd1V6d5
51300  1zi7xx7UVEFkmKfv06H8x0
51301  3UmaczJpikHgJFyBTAJVoz
51302  2iNqdCchlUZEgjJbQyZf8T
51303  5uEYRdEIh9Bo4fpjDd4Na9
51304  0ydyIEJ02X3kcZ6Bop6sHO
51305  0RGp4KA9wvndxqPIWoKwnD
51306  5f3PgI4zW2oErM3j3MWTWW
51307  0e9DDb2TnNwSv8lV1EpMuD
51308  6wWxQMhQgOCbmQkdOGslT4
51309  0TzpHT6hJ5pb3P6CqIduh3
51310  1a9fgoiGXoWmaFm60n1YeK
51311  20tnxv4NAzTCayQQln3EZP
51312  50BYymJYX2k7hnmfiXnYXs
51313  0WNCYgCd33LnBnw22WFuq8
51314  74qF0JeFMVilMEeFDiQZ48
51315  3YV4Go0hpYXjGTGLJXjfda
51316  1orM67pmkNc4alrZkWjYkV
51317  5uuVGnkZEFHBz8unViC3iA
51318  4r0LAir7t2WbMTae52XOo7
51319  2a7zxjZ1I88Z6sYm0ThuSc
51320  7FIWs0pqAYbP91WWM0vlTQ
51321  2wkVnwWcT3DgxQU0oifynE
51322  3K3mo4LoxPKk18oqIC3hQC
51323  6OgjDxorTU4qeLvVuB9zoW
51324  6MT5BRtVm18LrgqSrLnJuG
51325  5pOY1Vg2TIIbVBfR6yAg0C
51326  0uk9sQ7MjK0CdAUinD4xBV
51327  6RVmuLStrBGHGJ0CJhRh0U
51328  62jZHuAKzWsNLsAivOIbF3
51329  0vbisbhaTk92sEVKVkl66k
51330  2oEHcVe21whTKWQBqRAYPp
51331  1DzMKLVGK9JXR6Gu6LDhIb
51332  10l9RI8IHp1Z7b7dM3tMSv
51333  5FJEL8TOiQEWbD2QHYqprf
51334  46nTvkhLN9xQEVW7Q5Ojp2
51335  3cGGbBUCRL2nurtbbrGkL4
51336  4sAgnJgFJjhG8wNfqc1tlj
51337  2TCrYxhFs1CTFupauXzbIm
51338  5aNAawi2jFEe0qGPJSogRp
51339  4ngIVcfL0Pm564bTpDIS8H
51340  2BcPFQ7nrtUObgAs72xaac
51341  616iXZO76Rq81MEfFBktME
51342  4y5nWVseWL0cYo3yHDKEgE
51343  2J2da9welNmoeeBDLl9fUk
51344  2RB3zzgxWc2RRBaJOkSEka
51345  4NQBqInyE7zvjIiP4j1dmy
51346  4BWOTlwOwhdOGRZni7nxin
51347  23Hakma2pAUDAGnyp4TLc1
51348  4FL8i7miD18FuMN08XGKcM
51349  4sCcDvX30uu39ozvxcRsqB
51350  3GCdLUSnKSMJhs4Tj6CV3s
51351  322TxW77VZdX9gHynK5Xue
51352  1PckUlxKqWQs3RlWXVBLw3
51353  6E6BCsQHXDAdXsrL7zV71N
51354  7n6AQKpZUGiJM2auF3yuDY
51355  08j9wzt7Q9Ucq1IrpD4GVq
51356  1zPlQih67ZvC3Xp6c2dxUI
51357  43mHckutQvJr49nT0UvRxy
51358  6AooRgSRDzbCYL4NZ4RCjU
51359  4OUAXw3SXI7bUiNtKC7ErW
51360  2N0oWy78RT70bW10QfIVHT
51361  52XpQt2fDLozI4qlhYvWl0
51362  1SFwLNaHkV8WhW3ud1GBIJ
51363  49TNlAQZXmFBteKZBF9rj0
51364  7B8WJgjZzzV1uS7v9z8FGX
51365  000RDCYioLteXcutOjeweY
51366  1xoQjCAP6a63tZXbsMziXk
51367  0gzu5mm36VJH2Zqu8sQPTf
51368  2mwBSO58y92EYmEFpDfmS7
51369  7Ie9W94M7OjPoZVV216Xus
51370  6BWssu3CWDgkZXHnSWiwSh
51371  0eu4C55hL6x29mmeAjytzC
51372  2QkUgk0UgTYBViwZKN0l3H
51373  4mBMyfaNeG40BUBm3DP5xV
51374  2UKK9UEbKlykbmLVP1zWIQ
51375  04VUjNx30IrigVZU3CQmrQ
51376  4LMQWQqpweFys6elnjBvR6
51377  6ZmtxXUXRVjxOhugKkmerC
51378  1DTT5r0ImuzOXi1iNZ5o9C
51379  1sroeVHD561J3z28gphnlf
51380  3CYcfkVQbUPjnljKdKA8H1
51381  22kRCQPyNXWZSQEcDvCmGD
51382  01NsPGMDWGOrNWK9QylpHw
51383  0UGoctruuLwFBXHjXpDpcd
51384  3B4Wf3Fo11BXSuVPi1dtDO
51385  24GlSNySJ9tAwkvZPuVb63
51386  0obvnPQaTe8fRAQHWyOWBv
51387  2cVJDlu9jmkPUeuJxA6v8i
51388  7qpLvsz6U3TSYxLIg82tVd
51389  6RXJKdpBp6AVL6H6sHyNp0
51390  4YIhJmihoXwjtbY4vsV9Nh
51391  67KTXqxMEyBMq3LApqCgNV
51392  5y8DBJkNfWYPpXUWQmPscR
51393  228g1NgJgOs36q9m1McKps
51394  6cSpp45tNFg80xi4f8ZBAY
51395  5E73WRgx5QymAZBW3kbTR0
51396  4KPWs0tm7JgdIak35XZLoL
51397  4c8KffBxeK8cTUj9wEOGl7
51398  12D1SCxBRDjbROUa5GQkf1
51399  2QnaC2GQiRytjynYWqcxsa
51400  7rnqq7955ubY95MRPiRpue
51401  15JINEqzVMv3SvJTAXAKED
51402  4cacyP5c3PMlfnyjpg13xW
51403  5lNQ2M1yJ1HAQGHgUfLlY3
51404  5pZEThCuY84PiajfmeOJ3i
51405  7tavmiMMEibizGOiXoozar
51406  3GAekGYLRRWGx0fSNhjZEU
51407  6q4IEBv1tWq3MHIBnCYYSS
51408  55drdNAFl8HaAo0yqnU2EJ
51409  1XWCqa4qi714D7THtTk4Xk
51410  1KfwlyvJQD1TA70RyC0Byd
51411  2GfARslWOjzRUtqCemkJmF
51412  6oBPzKy4CmsnROO8vH8MjA
51413  6GTN9TiAMkDKTy6RatsP8l
51414  4P0r0yO7HNPvOra7BHGixH
51415  331CFIHeefOVTC4F8cmYTL
51416  6MgM415sTN6TUh3B3YlWCW
51417  5u1cWcqIX6sbKiVJn8PR86
51418  4DmD47YgOMFzBZnehrmWj7
51419  7JoI4RoMUdZXBgIs7ZkhHV
51420  1nYAl9wYboVclul2fkCiyr
51421  4xZwBITWeGPWVTDVmLfuDf
51422  1afMigcYdKpRwDf8IyXnln
51423  6HIkxxaASDhaXdcMa2PFRB
51424  7fduswfw6pp8e1U4k5aF0R
51425  16ejic4tkC645g8FwuqIHA
51426  16wcqaM2abvltq2RciqfYZ
51427  3j4srp6dMT39MLxx6XEbOR
51428  5SMCxyEHdPJJf9VFwFYo4B
51429  6MMB9EotY47IvE71cdiKS5
51430  2W3Pabwcki4u8XZhxWLkEw
51431  1eXeb2RwfAn6iKUPmGyfs4
51432  1O3WfEwaSpsgZ6tw8jNT8I
51433  7qtz1mNAD4CQMiIcfFRbj7
51434  2X0eUvX06w5DC1ecN2g4Bo
51435  20Nm2cPyMiIStyDuZEh4DP
51436  2wHTMZwkLbpM6LNkUBs2Xt
51437  1jBIlZyCUOylXmEuLNvGCQ
51438  2gLUbowsRFFwhmlAS3hZ5i
51439  6r8DKNt9BlrOICBpqUVlsP
51440  0rAuw3mWHHQZm5iczkEJHU
51441  45ffClKkj594CkU0naaLrM
51442  2eib87FpOijGfDL2jqPlo6
51443  7xj2n1FdeULoyFrOWDPLDA
51444  3mfsGLEmKF6sWTqFQzZ4aF
51445  5pILd3WHCjJa8trmnjfRBO
51446  7ItTtfj4WQHe4SKNM22QFT
51447  5tGeFA0C9YOISUdr0uo4St
51448  4ZrtOchitJWVfyyHJd4tX5
51449  5Gk36wgJ5QwSCS2WFqlpRf
51450  68Dni7IE4VyPkTOH9mRWHr
51451  6PSGzXHJaQogb2G8m8gGZZ
51452  4UKCKdYiLN6IMA5ZESUTL7
51453  3eekarcy7kvN4yt5ZFzltW
51454  2YMlGrhVHdbXeDejv0R77R
51455  2RBkVQwpkDeYytMTQwjyTk
51456  1vDK1yoxF0mOkckgDfPDj2
51457  3HHOY3hOZRJf1ORqNSDS8B
51458  4C6Uex2ILwJi9sZXRdmqXp
51459  3JbIyrSNumxS5LHpAvLYF5
51460  6cdiviyVL3tFYE1eDcmUzL
51461  4dCLUBJwtZwc4HYXvfcpyP
51462  4Ft4Tj0l8kzfKBv8vGuR4t
51463  2YpeDb67231RjR0MgVLzsG
51464  1MGvSryQcSR7zsNG4lQOjN
51465  32U1XMh3DKlm45uvpofhvY
51466  7nMFbXSPRgJDE01Tbfx7Qe
51467  5dvGOTBXFSgpKddB6MGe0P
51468  4VUpM5CFGeaeWY7akhQwQB
51469  1tEto4JrqNmBZFH5uAiYqb
51470  5NeP5LxzlLaGlsVFHviHUj
51471  4tBMbRwLJa5BjwJ6FrBlks
51472  445XlOVyjyGvdrQfkQA1lg
51473  3kwHHD0mE5Tv4RTMZwi3kK
51474  2gNC2UZGVSK0iW4Ymc56na
51475  4enBboQxIXJ104dP5MFQGw
51476  6Y1cH3RzDCMWGQtOS0HmP8
51477  2zVOFcdPAurQMbP1D6czwo
51478  4dJrjWtAhEkW7VdPYSL1Ip
51479  1LFTKTSfPQRM3a8mOvNtnE
51480  17TjJhR1wrGFW58aJnHpNC
51481  7d7whQmni6ZvmfkWE5XEAX
51482  724GJE6FqTdNKMARgAr6i7
51483  6wKu6jqzVtxikYztRUWkoS
51484  5vwpOLQh2PpIbuJSjHhFwZ
51485  4yurVSNjaPBKkOpbZWtuJO
51486  0eFNR4nWuhgvBw6vSDyVHj
51487  5zjFsuLrTM5sp6coribhCa
51488  0iJPMG79hgWnDHjufnoplb
51489  4e3Zs0VTWbGw4PmOwOZwZR
51490  7mNQwVYgoB3mtjkjCKsbXM
51491  6RdJrnkVsY7nR32bkVSIp1
51492  79HOkvmqDClCE9YAUApCP4
51493  0d4mAx3fJvSJQPkREvjMDT
51494  6TgqGNKs3qOO3Cpj7fJi40
51495  10Hx18HoNVjnsBKwQIH9eX
51496  15kWrrwlkBNJnTYDvyYfBS
51497  5w3gA8oGndl475y4xICRYF
51498  6OcnzwOfKQc0ZWJoMuFQam
51499  50a2d6g5kpr3wt98Jw2Tns
51500  7KXjTSCq5nL1LoYtL7XAwS
51501  1rDQ4oMwGJI7B4tovsBOxc
51502  5k38wzpLb15YgncyWdTZE4
51503  4woTEX1wYOTGDqNXuavlRC
51504  6gBFPUFcJLzWGx4lenP6h2
51505  0usNFsDDoVMYVE732zM3QI
51506  6CzMKOYzhBXzZszsy4yFIG
51507  1r8ZCjfrQxoy2wVaBUbpwg
51508  27OeeYzk6klgBh83TSvGMA
51509  53DXM0bHfB7xkqJZYlksuh
51510  5e0sqZrtakU2phj6IFxf79
51511  7GfdU12uRL2xtSQcRXmqNN
51512  4jRoXx97M0sSZBfwMkBEDV
51513  3F0I9AkbRwz12yz7Hxn0bF
51514  7MAw33OyE75nD1om6y9bHR
51515  2E2G88mTTJjbbmEpqTkbaV
51516  7HNHIRAYrKeuobsj6n3l1y
51517  74Qks1cW4TkoZYUPUHTq46
51518  3OZr3vo7SmYpn5XqeQEAOM
51519  1vSXwYeKnzsVvekSpqVabx
51520  0ZsSFv9dqF4O6MReTo1JBH
51521  7yn0E97MoGLBaW8mqIwqNr
51522  6ElANRiS4S25oIn361o8Ye
51523  3kpYJjvM8Ja6btr5hEJLWc
51524  2C0Bdvg3JgpMfKlmIdO8Fl
51525  5I3Xih0C2ID3fqngBrBbGv
51526  4N0TO4VfONQDwynV2khBL1
51527  6IdUSDkIkBP7ZmTIZrZiVV
51528  1FHf9qmNWwDsZYdLnteiQI
51529  79MHQXymz8cGX8OOAjXn7J
51530  7KqmDr9lTjwXnX5krMIKiC
51531  6fP7zEaXUaGmzTDyvA79Ng
51532  4xgXA4ipRmQqrrvT6ZBSRX
51533  2puCdLnS6sKRdbEabw4bjP
51534  1gTD1rUFgz05rRyMvPPRtX
51535  7ywkgsA1ESYARdGqqbundd
51536  6h1JK4zvCvvSHJFFVG3Vqf
51537  3NEqymGUS8TrDlaJi9HkI6
51538  2dR6XZWFAfbH7jAb1r5qcE
51539  7HZycMIpBHgDa8Re6S2UcR
51540  4lGSIRb6BlkjdudJ7T41Ai
51541  40IGDj8y6mbq3ZGYV8Zo60
51542  2Racq7HrXkYvF8w9zXvlTp
51543  16fWSYYJToYWTuFL9OocdT
51544  1p4znbL4AT5p3qMWFLhCdJ
51545  4JlUDMr4cmVNXzk9xc1lXS
51546  6cbW2scRULV7RnFT4u8gnA
51547  62lmjlPu5Vwd3h18FMSz1G
51548  79blZUG11a6vtTL3Nt9J78
51549  2kbxGCtWSV0f1ON720Bd4O
51550  4vVTI94F9uJ8lHNDWKv0i2
51551  4BExko3OEVRa3RI50gpFgA
51552  5pAo2q7eVt65OSkwYgqhHl
51553  3yiEaNgKJWN3gCfHfB8Q1u
51554  2z718tUE8RwkPlJ3Oc2RcW
51555  58prIObJ1GMpyG51jnMjeS
51556  6XjFkmGaUioM800RmFSV8r
51557  0RwQG3x5q1HE0CDetUuYFk
51558  3cvVjjZU0IWuTsiaa5F7k3
51559  6oloWgrErtc8dG2WiV55gn
51560  41vUI66skZegzFHxwMkk8t
51561  0tPyKRyhswSCMlOfKbR4Au
51562  7JQJH07Mo4UQDBBVR2cKNh
51563  5jGbxKNLOEWZoOmVpcYbJO
51564  0Rz7S7DSsiROEWR2mH5DwI
51565  5QNFpjUpjZ2X9YgzIdDDhy
51566  1qkjQxTfIyRtZPK1nYWTvw
51567  6I2tOKBqqIUhxEVKnolGjx
51568  0EvlAy9hx3kbnqfgg8VX7z
51569  4JLeg2RgRkPg5Y4BLWwQjn
51570  5RgN2LdqCGnxztU1cTNJjf
51571  2ajQyTRxBRbPLaMmnO1SHj
51572  19b4vDb9mrs4WFh42ySOi7
51573  0osMWCvwxing4xMPbMEMJY
51574  0mCPTRXERMDFEFLBjE99ZU
51575  7blZJHDpI8TWDm2a2Q7QS7
51576  61tnfFfea71XruDZadOUmu
51577  4YU2HODpoaTGigDJYCv5xM
51578  5oibpY8nzNR2uCPKMzLeK0
51579  3n2lUfmtaYuqMSR8tDo8F0
51580  1eKf1hCEVQbRDsOIrY0U3M
51581  5ONoPS5pUghXhLhqaKsFal
51582  01xqHIwd7hQLROgelUQ6w2
51583  0Nb0A0yuiYHiVyMyZm0Wh8
51584  4ZcKL6BGQCzAn5aUZK0dYw
51585  676A9Z6QiBWPIJm0UB1w61
51586  34qxi6dCXAb90enc88oYfY
51587  0pp7ZaS8BM0t3iB3DzioJ0
51588  74w5vyOFuin2Zu4GsP8paJ
51589  6C75pCSzgl5EJtvIuTqmyO
51590  3F9SGJzTCkqIS3d99iz0p7
51591  4ZSFKEQMre7LJUkUEW28oA
51592  6fCuXxMlr6Wz0MzQgtQLgd
51593  6rJNWcdEfyBJuy1X2bENL7
51594  6Rnmu3xQeJMVc6OvACEBES
51595  3w7JADbLdKE1Qta6aH0SC6
51596  2NEhxLuoy6tKtLhm7D6Sp0
51597  53zYfvOxlsHZv89MmpY1D5
51598  0FtOxBrDP67usYNbqOuy7T
51599  3jOdjEVdD0mbsGWhpemZBG
51600  1fewSx2d5KIZ04wsooEBOz
51601  4chxJYv0qsOKQukt6cKp97
51602  5SAgi6ZXqpCWQADP8XyRDY
51603  0QHEWicUbdyWuHsMcVd1Ka
51604  0pPMSxTHDxROblb7yID8Ar
51605  342pJxy678kgQrZXCL9RG7
51606  4uW8CuyO9r7vOXgYf1eqCz
51607  0BV0AYGLVlu2SdjN3J9twp
51608  2KJUr9U6a3balnh1W7hDwZ
51609  4HEzmqZuqVk3qSwD6Dtk6K
51610  5DIt4eq2D6CZjX1s5jwrnP
51611  7DonyrUlcVcrtk28mqvWNL
51612  3w9i7F6nze5mODaJstlVWt
51613  3Oh2FwWbnKIAyUE2gToFYu
51614  6or1bKJiZ06IlK0vFvY75k
51615  3LlEnO0INKAExVe4JMi7p7
51616  4iLLyEZv9m2koIAjLDA04i
51617  3Fr1WmziIKmhU9s5fNKZrQ
51618  2PxZSFOv7RebkeSEwQTjr7
51619  7fm1Nbus8X19wI4oz6FFcb
51620  0EKqoSFmZW4dqaJvlEJtMe
51621  5YctxMWPzEXjnmHLA0mYUN
51622  0M7kvopFlauSwmfObUPzAx
51623  01AKiTk6iF60Kpvitd1Ih1
51624  5I2wbDvSI98HLVB42YO9sU
51625  1QhGycrwJKEOBKeVFOEPak
51626  1VQIWTMzZUeJM5HmLwaKEp
51627  5JzX4z7nOrstlzGbwd1hOJ
51628  06vqoU6oPRPPkILm8tyBRo
51629  1PyLgsWqPsYyce2sAYOo7c
51630  7LMWOSOTxSMxABmkpG2YK3
51631  21NimLGgXhfEbIXsIiPHXy
51632  3uZiNvBNQldjl4OJiKsuxe
51633  298atiKYvG84VfbXNbZiX5
51634  3ym8ZuRQtZ7rSEbXkT3eJE
51635  62KDpF0Hv7KJLZrrKXsz8r
51636  3G1o1dkJIyY38yfiVDkwNP
51637  3u0UC2O76OTzrYpioBUQiN
51638  6SBiO0ai9ntitAxZvyqpsw
51639  6GFtWQYco30oKpMr5xJwy2
51640  52SEeWxiAu87QWWA72Fip8
51641  5oibpY8nzNR2uCPKMzLeK0
51642  2xE3KRNQc2AGpV95NsvGfg
51643  0oNzFzjf5eDRnvpGe7u2r2
51644  0mhMSxIx2XnXCF7PDLjUGG
51645  0G598RMjEm3GoWVNBvbAId
51646  1AhTJuf8NnyCcXuSiEa1HP
51647  274sq7UtbMqE8hoswJPagJ
51648  74ke9u10rIeCwTU0KOT6C5
51649  4KaHGrCbg4hwu25RzUO4Br
51650  0fX4oNGBWO3dSGUZcVdVV2
51651  7AQim7LbvFVZJE3O8TYgf2
51652  7iL6o9tox1zgHpKUfh9vuC
51653  1C5e7ZRscn79tjMEc3swc7
51654  7q7eYVerltlW2sYBuga6Mj
51655  3hVc5y5mbcIEPADRGGGru9
51656  2qPNdVlqZl1cYqsNc3MXnA
51657  1aUfggX5E0nKDikNuiDQ3D
51658  0RFxx8rwddnW4j9COvLmGK
51659  12V0iduYsoXxsQYTSeFB2H
51660  6UeMjHhzYnidHi7I4isoGg
51661  0TeH0rRFmef6eqk86MPyUA
51662  78PDj0uocOvtSJCdOt65qy
51663  02Z90kqEwTvBQEOmP6jxyk
51664  2tTmW7RDtMQtBk7m2rYeSw

In [15]:
df.columns

Index(['track_id', 'artists', 'album_name', 'track_name', 'popularity',
       'duration_ms', 'explicit', 'danceability', 'energy', 'key', 'loudness',
       'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'time_signature', 'track_genre'],
      dtype='object')

In [18]:
feature_cols = ['popularity', 'danceability', 'energy', 'loudness', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo']
metadata_cols = ['track_id', 'artists', 'album_name', 'track_name',]

df[feature_cols].describe()

,popularity,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo
count,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000
mean,33.238535,0.566800,0.641383,-8.258960,0.084652,0.314910,0.156050,0.213553,0.474068,122.147837
std,22.305078,0.173542,0.251529,5.029337,0.105732,0.332523,0.309555,0.190378,0.259261,29.978197
min,0.000000,0.000000,0.000000,-49.531000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,17.000000,0.456000,0.472000,-10.013000,0.035900,0.016900,0.000000,0.098000,0.260000,99.218750
50%,35.000000,0.580000,0.685000,-7.004000,0.048900,0.169000,0.000042,0.132000,0.464000,122.017000
75%,50.000000,0.695000,0.854000,-5.003000,0.084500,0.598000,0.049000,0.273000,0.683000,140.071000
max,100.000000,0.985000,1.000000,4.532000,0.965000,0.996000,1.000000,1.000000,0.995000,243.372000

In [20]:
scaler = StandardScaler()
X = scaler.fit_transform(df[feature_cols])
X.shape
X

array([[ 1.78262719,  0.62924424, -0.71714792, ...,  0.75874327,
         0.92930586, -1.14186279],
       [ 0.97563254, -0.84590798, -1.88997974, ..., -0.59121068,
        -0.79868969, -1.48971712],
       [ 1.06529861, -0.74218634, -1.12266943, ..., -0.50716686,
        -1.36568823, -1.528312  ],
       ...,
       [-0.50385765,  0.35841551, -1.24194046, ..., -0.68103252,
         1.03730558,  0.34125493],
       [ 0.34797004,  0.11639835, -0.53824138, ...,  0.29650223,
        -0.23554828,  0.4607423 ],
       [-0.50385765, -0.23510276, -0.6137797 , ..., -0.65266773,
         0.90230593, -1.43270877]])

In [ ]:
descr_cols = ['track_id', 'artists', 'album_name', 'track_name']
df = df[descr_cols][df['artists']=='Drake']