In [2]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [19]:
df = pd.read_csv('dataset.csv')
# df = df.drop(columns = 'Unnamed: 0')
pd.reset_option('display.max_rows')
#pd.concat(g for _, g in df.groupby("track_name") if len(g) > 1)
#pd.options.display.max_rows = None
#df[df['track_genre']=="hip-hop"]
# df['score']=0
# df[df['track_id']=='6DCZcSspjsKoFjzjrWoCdn']['score'].values[0]
df.dtypes

Unnamed: 0            int64
track_id             object
artists              object
album_name           object
track_name           object
popularity            int64
duration_ms           int64
explicit               bool
danceability        float64
energy              float64
key                   int64
loudness            float64
mode                  int64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
tempo               float64
time_signature        int64
track_genre          object
dtype: object

In [17]:
df.dtypes

track_id             object
artists              object
album_name           object
track_name           object
popularity            int64
duration_ms           int64
explicit               bool
danceability        float64
energy              float64
key                   int64
loudness            float64
mode                  int64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
tempo               float64
time_signature        int64
track_genre          object
score                 int64
dtype: object

In [5]:
feature_cols = ['popularity', 'danceability', 'energy', 'loudness', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo']
metadata_cols = ['track_id', 'artists', 'album_name', 'track_name',]

df[feature_cols].describe()

,popularity,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo
count,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000
mean,33.238535,0.566800,0.641383,-8.258960,0.084652,0.314910,0.156050,0.213553,0.474068,122.147837
std,22.305078,0.173542,0.251529,5.029337,0.105732,0.332523,0.309555,0.190378,0.259261,29.978197
min,0.000000,0.000000,0.000000,-49.531000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,17.000000,0.456000,0.472000,-10.013000,0.035900,0.016900,0.000000,0.098000,0.260000,99.218750
50%,35.000000,0.580000,0.685000,-7.004000,0.048900,0.169000,0.000042,0.132000,0.464000,122.017000
75%,50.000000,0.695000,0.854000,-5.003000,0.084500,0.598000,0.049000,0.273000,0.683000,140.071000
max,100.000000,0.985000,1.000000,4.532000,0.965000,0.996000,1.000000,1.000000,0.995000,243.372000

In [6]:
scaler = StandardScaler()
X = scaler.fit_transform(df[feature_cols])
X.shape
X

array([[ 1.78262719,  0.62924424, -0.71714792, ...,  0.75874327,
         0.92930586, -1.14186279],
       [ 0.97563254, -0.84590798, -1.88997974, ..., -0.59121068,
        -0.79868969, -1.48971712],
       [ 1.06529861, -0.74218634, -1.12266943, ..., -0.50716686,
        -1.36568823, -1.528312  ],
       ...,
       [-0.50385765,  0.35841551, -1.24194046, ..., -0.68103252,
         1.03730558,  0.34125493],
       [ 0.34797004,  0.11639835, -0.53824138, ...,  0.29650223,
        -0.23554828,  0.4607423 ],
       [-0.50385765, -0.23510276, -0.6137797 , ..., -0.65266773,
         0.90230593, -1.43270877]])

In [7]:
descr_cols = ['track_id', 'artists', 'album_name', 'track_name']
df = df[descr_cols][df['artists']=='Drake']

In [8]:
df[df['track_name']=="NADODI"].sort_values('popularity', ascending=False)

KeyError: 'popularity'

In [ ]:
df['score']=0
df

                     track_id artists album_name  track_name  score
51250  6DCZcSspjsKoFjzjrWoCdn   Drake   Scorpion  God's Plan      0

In [9]:
df.describe()

                      track_id artists album_name  track_name
count                        1       1          1           1
unique                       1       1          1           1
top     6DCZcSspjsKoFjzjrWoCdn   Drake   Scorpion  God's Plan
freq                         1       1          1           1